#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#efece8"
bspc config active_border_color "#efece8"
bspc config focused_border_color "#efece8"
bspc config urgent_border_color "#ce868d"
bspc config presel_border_color "#88c0d0"
bspc config border_width 0
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale /home/dev/.config/wallpaper/wallpaper.png
fcitx5 &
dunst &
$HOME/.scripts/check_usage.sh
export PATH="${PATH}:/home/dev/.local/bin"
picom &
$HOME/.config/polybar/launch.sh
