[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular"}
# normal = { family = "Fira Code", style = "SemiBold"}
size = 12

[colors]
selection = { text = "CellForeground", background = "#6c7086" }

[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.normal]
black = '#181825'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#89dceb'
white = '#cdd6f4'

[colors.bright]
black = '#313244'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#89dceb'
white = '#cdd6f4'

[cursor]
style = { shape = "Beam" }
