"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = "session"
    style = "plain"
    background = 'transparent'
    foreground = "#a6e3a1"
    foreground_templates = [ "{{ if .Root }}#f38ba8{{ end }}" ] 
    template = "{{ if .SSHSession }}{{ .HostName }}{{ end }}  {{ .UserName }}"
  
  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "#89b4fa"
    background = 'transparent'
    template = "  {{ .Path }} "
    
    [blocks.segments.properties]
      folder_icon = ""
      style = "full"
  
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = "#a6adc8"
    background = 'transparent'
    template = "{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    
    [blocks.segments.properties]
      fetch_upstream_icon = true
      fetch_stash_count = true
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  
  [[blocks.segments]]
    type = "status"
    style = 'plain'
    foreground = "#eba0ac"
    background = 'transparent'
    template = "{{ if eq .Code 0 }}<#74c7ec>0</>{{ else }}<#f38ba8></> {{ .Code }}{{ end }}"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    background = 'transparent'
    foreground = "#c0caf5"
    template = " <#94e2d5>󱤦</> {{ .FormattedMs }} "
    
    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "#fab387"
    template = " {{ .CurrentDate | date .Format }}"
  
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = '#bac2de'
    template = "❯"

[transient_prompt]
  foreground = '#bac2de'
  background = 'transparent'
  template = "❯"
